# Generated by Django 3.2.6 on 2022-05-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOffer',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('Nameofoffer', models.CharField(max_length=100)),
                ('Typeofoffer', models.CharField(max_length=100)),
                ('Startingdate', models.CharField(max_length=100)),
                ('Endingdate', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('productprice', models.CharField(max_length=100)),
                ('featureofproduct', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('productid', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clothpictures/')),
            ],
        ),
        migrations.CreateModel(
            name='NewRegister',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('cpassword', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clothpictures/')),
            ],
        ),
        migrations.CreateModel(
            name='user1',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('Productid', models.CharField(max_length=100)),
                ('productname', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('productid2', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clothpictures/')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
